apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: jenkins-slave-scala
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    name: jenkins-slave-scala
    labels:
      app: jenkins-slave-scala
  spec:
    dockerImageRepository: jenkins-slave-scala
    lookupPolicy:
      local: false
