apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: jenkins-slave-nodejs8-vips
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    name: jenkins-slave-nodejs8-vips
    labels:
      app: jenkins-slave-nodejs8-vips
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-slave-nodejs8-vips:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: nodejs8-vips
      git:
        ref: production
        uri: ${REPO_BASE}/opendevstack/jenkins-slaves-dockerimages.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
          - name: NEXUS_HOST
            value: ${NEXUS_URL}
          - name: NEXUS_AUTH
            value: ${NEXUS_AUTH}
      type: Docker
    triggers: []
parameters:
- name: NEXUS_URL
  required: true
- name: NEXUS_AUTH
  required: true
- name: REPO_BASE
  required: true
