apiVersion: v1
kind: Template
labels:
  template: component-pipeline
message: |-
  For more information about using this template, including OpenShift considerations, see the documentation (TODO).
metadata:
  annotations:
    description: |-
      This templates performs the basic setup for component pipelines.
    iconClass: icon-nodejs
    openshift.io/display-name: Component Pipeline
    template.openshift.io/long-description: This template defines resources needed
      to develop an application, esp. the build pipeline
  name: component-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${COMPONENT}-${ENV}
  spec:
    source:
      type: Git
      git:
        uri: ${BITBUCKET_REPO}
        ref: master
      sourceSecret:
        name: "cd-user-with-password"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
      type: Generic
    triggers:
      - type: Generic
        generic:
          secret: ${TRIGGER_SECRET}
parameters:
- description: The name of the application project.
  displayName: Project
  name: PROJECT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: The name of the component
  displayName: Component
  name: COMPONENT
  required: true
- description: Bitbucket repo
  name: BITBUCKET_REPO
  required: true
- description: Trigger secret
  name: TRIGGER_SECRET
  value: secret101
