apiVersion: v1
kind: Template
labels:
  template: component-route-template
message: |-
  For more information about using this template, including OpenShift considerations, see the documentation (TODO).
metadata:
  annotations:
    description: |-
      This templates performs the setup or a route for a component.
    iconClass: icon-nodejs
    openshift.io/display-name: Component Template
    template.openshift.io/long-description: This template defines resources needed
      to develop an application, including a build configuration, application
      deployment configuration.
  name: component-route
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${PROJECT}
        component: ${COMPONENT}
        env: ${ENV}
      name: ${COMPONENT}
      namespace: ${PROJECT}-${ENV}
    spec:
      host: 
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${COMPONENT}
        weight: 100
      wildcardPolicy: None
parameters:
- description: The name of the application project.
  displayName: Project
  name: PROJECT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: The name of the component
  displayName: Component
  name: COMPONENT
  required: true
